global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'us-lb-01'
    static_configs:
      - targets: ['us-lb-01.emurgo-rnd.com:9101']
        labels:
          alias: us-lb-01

  - job_name: 'us-lb-02'
    static_configs:
      - targets: ['us-lb-02.emurgo-rnd.com:9101']
        labels:
          alias: us-lb-02

  - job_name: 'eu-lb-01'
    static_configs:
      - targets: ['eu-lb-01.emurgo-rnd.com:9101']
        labels:
          alias: eu-lb-01

  - job_name: 'eu-lb-02'
    static_configs:
      - targets: ['eu-lb-02.emurgo-rnd.com:9101']
        labels:
          alias: eu-lb-02

  - job_name: 'sg-lb-01'
    static_configs:
      - targets: ['sg-lb-01.emurgo-rnd.com:9101']
        labels:
          alias: sg-lb-01

  - job_name: 'sg-lb-02'
    static_configs:
      - targets: ['sg-lb-02.emurgo-rnd.com:9101']
        labels:
          alias: sg-lb-02


